### ISSUE TITLE
脚本显示被安全设置列入黑名单

### ISSUE THREAD

**Issue by yinhaox** [zhangxujie2018/Hrbust-Auto-Eva#2]
如图，我用的是chrome87.0.4280.88浏览器和Tampermonkey管理器
![err](https://user-images.githubusercontent.com/33537497/103333894-77383480-4aaa-11eb-9e8a-25adb0ed7314.png)

**Comment by Leisurelybear** [comment]
@yinhaox 请问您Tampermonkey的安装方式？，在浏览器上   **【扩展程序 -> 管理扩展程序 -> Tampermonkey
详细信息 -> 】**  中的 **来源** 是否为：**Chrome 网上应用店**

**Comment by yinhaox** [comment]
来自谷歌应用商店




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhangxujie2018/Hrbust-Auto-Eva"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月31日(星期四) 凌晨0:37
收件人:&nbsp;"zhangxujie2018/Hrbust-Auto-Eva"<Hrbust-Auto-Eva@noreply.github.com&gt;;
抄送:&nbsp;"yinhao"<642283766@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [zhangxujie2018/Hrbust-Auto-Eva] 脚本显示被安全设置列入黑名单 (#2)





 
@yinhaox 请问您Tampermonkey的安装方式？，在浏览器上   【扩展程序 -&gt; 管理扩展程序 -&gt; Tampermonkey
 详细信息 -&gt; 】  中的 来源 是否为：Chrome 网上应用店

**Comment by yinhaox** [comment]
Tampermonkey Beta




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhangxujie2018/Hrbust-Auto-Eva"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月31日(星期四) 凌晨0:37
收件人:&nbsp;"zhangxujie2018/Hrbust-Auto-Eva"<Hrbust-Auto-Eva@noreply.github.com&gt;;
抄送:&nbsp;"yinhao"<642283766@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [zhangxujie2018/Hrbust-Auto-Eva] 脚本显示被安全设置列入黑名单 (#2)





 
@yinhaox 请问您Tampermonkey的安装方式？，在浏览器上   【扩展程序 -&gt; 管理扩展程序 -&gt; Tampermonkey
 详细信息 -&gt; 】  中的 来源 是否为：Chrome 网上应用店

**Comment by Leisurelybear** [comment]
@yinhaox 我的Chrome版本和你的一样，油猴插件是V4.11，我的运行没问题，我猜测是油猴插件的安全设定或者浏览器的安全设定原因，我去试一试能否复现你说的问题
